### ISSUE TITLE
CSP Options

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-security-header-optimization#3]
How do I enable the use of
'self'
'unsafe-eval'
'unsafe-inline'
with the plugin? Without these, I get numerous CSP violations.

**Comment by optimalisatie** [comment]
Hi AlphaDE,

You can simply add it as CSP directive. More information is in the documentation.

https://github.com/o10n-x/wordpress-security-header-optimization/tree/master/docs

```json
{
    "script-src": ["'self'", "'unsafe-eval'"]
}
```

You can also have a look at the JSON schema for the CSP directives:

https://github.com/o10n-x/wordpress-o10n-core/blob/master/schemas/csp.json
