### ISSUE TITLE
Add logging / reporting facility

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-security-header-optimization#4]
The security plugin, I am still currently using integrates a logging/reporting facility so I do not need to rely on external providers and can optionally change the configuration using the reports (by adding domains, ... to certain rulesets).

It would be great, if this plugin would get that, too.

From a privacy point of view, information would stay on site and (in Europe under GDPR) there is no need to give and process data elsewhere (or let the user's browser do that).

**Comment by optimalisatie** [comment]
Hi Andreas!

Thanks a lot for the feedback and suggestion!

The plugin provides two reporting options: `Report URI` and the latest [Reporting API](https://wicg.github.io/reporting/).

![image](https://user-images.githubusercontent.com/8843669/41218575-e3b79e18-6d5b-11e8-8140-e04354393082.png)

It would be possible to use a paid reporting service such as [report-uri.com](https://report-uri.com/) (from the author of [securityheaders.com](https://securityheaders.com/) / [scotthelme.co.uk](https://scotthelme.co.uk/)) or a local reporting service, which could be PHP or a Node.js server (with admin UI).

There are several PHP solutions to process CSP reports.

PHP: https://github.com/immrr/csp-report
PHP: https://mathiasbynens.be/notes/csp-reports
Node.js: https://github.com/seek-oss/csp-server
Node.js: https://github.com/c0nrad/csp-endpoint

The plugin intends to purely focus on providing optimization technologies. It enables logging using Report URI and Reporting API but it doesn't provide a full UI etc. Instead, it would promote the use of [report-uri.com](https://report-uri.com/) or one of the many existing server-side solutions.

**Comment by AlphaDE** [comment]
Ok, when I enable

 Enable new Reporting API report-to directive.

then this point is disabled again after saving.

**Comment by AlphaDE** [comment]
Also, after configuring, Firefox complains that there is not report-uri in the Content-Security-Policy statement and the header does not contain the report-uri url.
