### ISSUE TITLE
UI problem / report-uri not working 

### ISSUE THREAD

**Issue by AlphaDE** [o10n-x/wordpress-security-header-optimization#5]
1. When I enable

Enable new Reporting API report-to directive.

then this option is disabled again after saving.

2. After configuring, Firefox complains that there is not report-uri in the Content-Security-Policy statement and the header does not contain the report-uri url.

I tried configuring the report-to/report-uri in both the JSON and the configuration items of the CSP tab as well as setting up Reporting API tab.

```
{
  "default-src": [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    "https://maps.google.com",
    "https://maps.gstatic.com",
    "https://static.mydomain.de",
    "https://www.mydomain.de"
  ],
  "connect-src": [
    "https://www.mydomain.de"
  ],
  "font-src": [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com",
    "https://fonts.gstatic.com",
    "https://static.mydomain.de",
    "https://www.mydomain.de"
  ],
  "img-src": [
    "'self'",
    "data:",
    "https://maps.google.com",
    "https://maps.googleapis.com",
    "https://maps.gstatic.com",
    "https://static.mydomain.de",
    "https://www.mydomain.de",
    "https://www.gstatic.com"
  ],
  "script-src": [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    "https://maps.google.com",
    "https://ajax.googleapis.com",
    "https://maps.googleapis.com",
    "https://static.mydomain.de",
    "https://www.mydomain.de",
    "https://cdn.ampproject.org"
  ],
  "style-src": [
    "'self'",
    "'unsafe-eval'",
    "'unsafe-inline'",
    "https://ajax.googleapis.com",
    "https://fonts.googleapis.com",
    "https://static.mydomain.de",
    "https://www.mydomain.de"
  ],
  "sandbox": [
    "allow-forms",
    "allow-modals",
    "allow-orientation-lock",
    "allow-pointer-lock",
    "allow-popups",
    "allow-popups-to-escape-sandbox",
    "allow-presentation",
    "allow-same-origin",
    "allow-scripts",
    "allow-top-navigation"
  ],
  "upgrade-insecure-requests": true
}

```

**Comment by optimalisatie** [comment]
Hi Andreas,

Thank you for reporting the issue!

The `report-uri` is configured using a regular HTTP header. The plugin simply sends these headers and does nothing special that could cause the feature to not be present in Firefox browsers.

I noticed the following comment in Mozilla's documentation:

> In browsers that support report-to, the report-uri directive will be ignored.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

This would mean that you would be required to use the new [Reporting API](https://wicg.github.io/reporting/) to support newer Firefox browsers.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

The plugin supports the Reporting API and offers endpoint management.

![image](https://user-images.githubusercontent.com/8843669/41500576-a74a8ec6-7194-11e8-9c16-664610df2a9f.png)

**Comment by AlphaDE** [comment]
Jan, thx.

But there we are at the other problem... if I enable that and enter the group name and save it, it is disabled after reload.

So yet, the reporting is not working.

**Comment by optimalisatie** [comment]
`report-uri` and `report-to` were not saving for Content Security Policy.

The bug has been fixed in `v0.0.57`.

https://github.com/o10n-x/wordpress-security-header-optimization/releases/tag/0.0.57

**Comment by AlphaDE** [comment]
Thx for the fix.
The checkbox works now. If the checkbox for Report Api is enabled and the report-uri is in the JSON, then it is delivered twice to the browser as Firefox reports.

**Comment by optimalisatie** [comment]
The `report-uri` and `report-to` headers have been improved in the latest update `v0.0.58`.

https://github.com/o10n-x/wordpress-security-header-optimization/releases/tag/0.0.59

✓ Improved: `report-uri` and `report-to` from CSP directive JSON is merged with the form based configuration. 
✓ Improved: the `report-to` JSON schema now includes an option to define a group (string), a JSON object with a group config or an array of JSON objects with a group config.
✓ Improved: the `report-to` group config now supports the `endpoints` variant.

###### Updated JSON schemas:
CSP: https://github.com/o10n-x/wordpress-o10n-core/blob/master/schemas/csp.json
Headers: https://github.com/o10n-x/wordpress-o10n-core/blob/master/schemas/headers.json

### Group name
```json
{
  "report-to": "csp-endpoint"
}
```

### Single group
```json
{
  "report-to": {
      "group": "csp-endpoint",
      "max-age": 10886400,
      "endpoints": [
        {
          "url": "https://example.com/csp-reports"
        }
      ]
    }
}
```

### Multiple groups 
```json
{
  "report-to": [
    {
      "group": "csp-endpoint",
      "max-age": 10886400,
      "endpoints": [
        {
          "url": "https://example.com/csp-reports",
          "priority": 1,
          "weight": 1
        }
      ]
    },
    {
      "group": "hpkp-endpoint",
      "max-age": 10886400,
      "url": "https://example.com/hpkp-reports"
    }
  ]
}
```

**Comment by AlphaDE** [comment]
Thx, JSON editor of security plugin reports
.csp | should NOT have additional property: reportUri
.headers | should NOT have additional property: access-control-allow-enabled
.headers | should NOT have additional property: access-control-allow-enabled

After installing the update

**Comment by optimalisatie** [comment]
There was a warning added in the update details:

> ✓ Modified: renamed `reportUri` JSON parameter to `report-uri`. **Please update your configuration** [View JSON schema](https://github.com/o10n-x/wordpress-o10n-core/blob/master/schemas/csp.json)
> 
> https://github.com/o10n-x/wordpress-security-header-optimization/releases/tag/0.0.57

The motivation was to match it with `report-to` to make the JSON more consistent. It was better to do it now with just a few users. The plugins are in beta.
