### ISSUE TITLE
PHP method?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [o10n-x/wordpress-security-header-optimization#6]
I'd like to manage the CSP depending on some WordPress functions like is_admin(). Therefore, is it possible to manage the CSP through a PHP method? For example, something like:

`\O10n\csp('domain','type');`

**Comment by optimalisatie** [comment]
Hi Ahmed,

Thank you very much for the suggestion! 

We will add the methods in a next update.

**Comment by optimalisatie** [comment]
The method has been added in `v0.0.57`.

https://github.com/o10n-x/wordpress-security-header-optimization/releases/tag/0.0.57

### Set Content Security Policy

```php
// remove sandbox
\O10n\Security\csp('sandbox', false);

// set multiple directives
\O10n\Security\csp(array(
    'block-all-mixed-content' => true,
    'plugin-types' => array(
        "mime/type"
    )
));

// modify JSON configuration by WordPress filter
add_filter('o10n_csp_directives', function($directives) {

    // remove sandbox
    $directives['sandbox'] = false;

    // set custom directives
    $directives['block-all-mixed-content'] = true;

    return $directives;
    
}, 10, 1);
```
